#!/bin/bash
protected_branch="master"
current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$current_branch" = "$protected_branch" ]; then
    echo "ERROR: Direct push to $protected_branch is not allowed."
    exit 1
fi

exit 0
