package com.hluhovskyi.zero.icons

import com.hluhovskyi.zero.common.Id

internal object KnownIconIds {
    val cash: Id.Known = Id("cash")
    val bank: Id.Known = Id("bank")
    val creditCard: Id.Known = Id("credit_card")
    val wallet: Id.Known = Id("wallet")
    val crypto: Id.Known = Id("crypto")
    val salary: Id.Known = Id("salary")
    val savings: Id.Known = Id("savings")
    val atm: Id.Known = Id("atm")
    val currencyExchange: Id.Known = Id("currency_exchange")
    val receiptLong: Id.Known = Id("receipt_long")
    val trendingUp: Id.Known = Id("trending_up")
    val accountBalanceWallet: Id.Known = Id("account_balance_wallet")
    val payments: Id.Known = Id("payments")
    val monetizationOn: Id.Known = Id("monetization_on")
    val paid: Id.Known = Id("paid")
    val cardGiftcard: Id.Known = Id("card_giftcard")
    val balance: Id.Known = Id("balance")
    val pieChart: Id.Known = Id("pie_chart")
    val creditScore: Id.Known = Id("credit_score")
    val requestQuote: Id.Known = Id("request_quote")

    val flowers: Id.Known = Id("flowers")
    val grocery: Id.Known = Id("grocery")
    val fastfood: Id.Known = Id("fastfood")
    val restaurant: Id.Known = Id("restaurant")
    val localCafe: Id.Known = Id("local_cafe")
    val localBar: Id.Known = Id("local_bar")
    val bakeryDining: Id.Known = Id("bakery_dining")
    val lunchDining: Id.Known = Id("lunch_dining")
    val icecream: Id.Known = Id("icecream")
    val liquor: Id.Known = Id("liquor")

    val car: Id.Known = Id("car")
    val carRepair: Id.Known = Id("car_repair")
    val beach: Id.Known = Id("beach")
    val flight: Id.Known = Id("flight")
    val hotel: Id.Known = Id("hotel")
    val luggage: Id.Known = Id("luggage")
    val hiking: Id.Known = Id("hiking")

    val diamond: Id.Known = Id("diamond")
    val shoppingCart: Id.Known = Id("shopping_cart")
    val checkroom: Id.Known = Id("checkroom")
    val redeem: Id.Known = Id("redeem")
    val devices: Id.Known = Id("devices")
    val localMall: Id.Known = Id("local_mall")

    val gameController: Id.Known = Id("game_controller")
    val movie: Id.Known = Id("movie")
    val musicNote: Id.Known = Id("music_note")
    val headphones: Id.Known = Id("headphones")
    val theaterComedy: Id.Known = Id("theater_comedy")
    val tv: Id.Known = Id("tv")
    val confirmationNumber: Id.Known = Id("confirmation_number")

    val book: Id.Known = Id("book")
    val school: Id.Known = Id("school")
    val menuBook: Id.Known = Id("menu_book")
    val calculate: Id.Known = Id("calculate")

    val health: Id.Known = Id("health")
    val medication: Id.Known = Id("medication")
    val medicalServices: Id.Known = Id("medical_services")
    val fitnessCenter: Id.Known = Id("fitness_center")
    val spa: Id.Known = Id("spa")
    val psychology: Id.Known = Id("psychology")

    val bolt: Id.Known = Id("bolt")
    val waterDrop: Id.Known = Id("water_drop")
    val wifi: Id.Known = Id("wifi")
    val smartphone: Id.Known = Id("smartphone")
    val localFireDepartment: Id.Known = Id("local_fire_department")
    val subscriptions: Id.Known = Id("subscriptions")

    val home: Id.Known = Id("home")
    val chair: Id.Known = Id("chair")
    val bed: Id.Known = Id("bed")
    val cleaningServices: Id.Known = Id("cleaning_services")
    val build: Id.Known = Id("build")

    val gasStation: Id.Known = Id("gas_station")
    val localTaxi: Id.Known = Id("local_taxi")
    val train: Id.Known = Id("train")
    val directionsBus: Id.Known = Id("directions_bus")
    val directionsBike: Id.Known = Id("directions_bike")
    val localParking: Id.Known = Id("local_parking")
    val twoWheeler: Id.Known = Id("two_wheeler")

    val pets: Id.Known = Id("pets")
    val childCare: Id.Known = Id("child_care")
    val familyRestroom: Id.Known = Id("family_restroom")
    val volunteerActivism: Id.Known = Id("volunteer_activism")

    val work: Id.Known = Id("work")
    val businessCenter: Id.Known = Id("business_center")
    val computer: Id.Known = Id("computer")
    val badge: Id.Known = Id("badge")
}
